services:
  - type: web
    name: portafolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portafolio_django.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portafolio_django.settings
