services:
  - type: web
    name: portafolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn portafolio_django.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true  # Asegúrate de que esté generando una clave secreta en producción.
      - key: DEBUG
        value: false  # En producción, asegúrate de que DEBUG esté en False.
