services:
  - type: web
    name: portafolio-scar0k
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn portafolio_django.wsgi:application